spring:
  application:
    name: "KIIPS AI 챗봇"
  ai:
    openai:
      chat:
        options:
          model: "gpt-3.5-turbo"
          temperature: "0.7"
          max-tokens: 1000
  # 한국어 인코딩 설정
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 관리 엔드포인트 설정 (Docker 헬스체크용)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized